version: '3.8'

services:
  torero-platform:
    image: ghcr.io/torerodev/torero-container:latest
    ports:
      - "8000:8000"  # torero-api
      - "8001:8001"  # torero-ui
      - "8080:8080"  # torero-mcp
      - "2222:22"    # SSH access
    environment:
      - ENABLE_SSH_ADMIN=true
      - ENABLE_API=true
      - ENABLE_UI=true
      - UI_PORT=8001
      - DASHBOARD_REFRESH_INTERVAL=15
    volumes:
      - ./data:/home/admin/data
    command: >
      bash -c "
        runuser -u admin -- torero db import --repository https://github.com/torerodev/hello-torero.git import.yml &&
        sleep 10 &&
        runuser -u admin -- torero service run hello-python &&
        runuser -u admin -- torero service run hello-ansible &&
        if [ '$$ENABLE_SSH_ADMIN' = 'true' ]; then /usr/sbin/sshd -D; else tail -f /dev/null; fi
      "